Icinga/icinga-go-library

- database/column_map.go
- database/db.go
`ColumnMap` provides a cached mapping of structs exported fields to their database column names. By default, all exported struct fields are mapped to their database column names using snake case notation. The `-` (hyphen) directive for the db tag can be used to exclude certain fields. Since `ColumnMap` uses cache, the returned slice MUST NOT be modified directly.
> database: Introduce `ColumnMap`

- database/contracts.go
- database/db.go
This allows us to dynamically determine the constraint names used for the `UPSERT` and `INSERT IGNORE` statements for the PostgreSQL driver.
> Allow to dynamically define type constraint name

- .github/workflows/sql.yml
> GHA: SQL: don't override health checks

- database/db.go
Simply restores the deleted method `DB#BuildColumns()`, as there is no other direct way to generate columns, since the column mapper is hidden.
> Restore deleted `DB#BuildColumns()`

- .github/workflows/go.yml
- backoff/backoff.go
- config/config.go
- config/tls.go
- utils/utils.go
- version/version.go
Enables code annotations in case of failures and fixes the actions triggered by the main branch.
https://github.com/Icinga/icinga-go-library/actions/runs/7783022809/job/21220618068
This PR suppresses also some of the reported existing `gosec` errors and solves some of them as well and drops the `only-new-issue` flag set for the go linter.
```bash
$ gosec ./...
---
Results:
Summary:
Gosec  : dev
Files  : 40
Lines  : 4269
Nosec  : 4
Issues : 0
```
> workflows: Fix `gosec` errors & enable code annotations

- version/version.go
Currently, the hard-coded value "Icinga DB" is printed in the `... --version` output. This PR requires you now to provide the project name when using `version.Print()`.
> Make project name configurable

- com/atomic.go
- com/com.go
In all cases both code paths do exactly the same.
> com/: improve readability by removing redundant ifs

- types/binary.go
- types/bool.go
- types/unix_milli.go
- types/uuid.go
I.e. match receivers, don't require a *T if a T is fine, too.
> types.*: assert interface compliance not stricter than needed

- logging/journald_core.go
- logging/journald_core_test.go
As seen over at Icinga Notifications[0], the use of non-alphanumeric
characters for journaldCore causes fields to be silently discarded.
This was due to journald's field key validation, which is unfortunately
not very well documented. Looking at its implementation[1], this library
code could be adapted to ensure that valid field keys are always used.
[0]: https://github.com/Icinga/icinga-notifications/pull/254
[1]: https://github.com/systemd/systemd/blob/11d5e2b5fbf9f6bfa5763fd45b56829ad4f0777f/src/libsystemd/sd-journal/journal-file.c#L1703
> logging: Sanitize Journald Field Key Names

- redis/client.go
- redis/config.go
A Redis server might support multiple databases, allowing to use the same Redis for different applications. The database can either be configured for the configuration or later changed via [SELECT][0]. By default, the database 0 will be used.
While both the used go-redis library and even [Icinga 2][1] support this feature, we should expose this here and make this configurable.
As discussed in [Icinga DB issue #676][2], this is not something one might want to encourage all users to use. However, there are definitely setups where this option might come in handy.
[0]: https://redis.io/docs/latest/commands/select/
[1]: https://github.com/Icinga/icinga2/blob/bca1a8447af26313123183efa863f947f9590731/lib/icingadb/icingadb.ti#L23
[2]: https://github.com/Icinga/icingadb/issues/676
> redis: Configurable Database

- redis/client.go
- redis/config.go
The Redis ACL system was introduced with Redis 6.0. It introduced users with precisely granular permissions. This change allows Icinga DB to connect to a Redis with an ACL user.
> redis: Configurable Username

- database/config_test.go
- logging/config.go
- logging/config_test.go
- redis/config_test.go
For #41, as just requested by @Al2Klimov in <https://github.com/Icinga/icinga-go-library/pull/41#issuecomment-2269101306>.
> Tests for Introduce config.FromEnv()

- database/db.go
Introduces a `DB#ExecTx()` method on the `DB` receiver (cherry-picked from #18)
> Introduce `DB#ExecTx()` method

- database/db.go
In case of an error before committing the database transaction, the function exits but does not rollback the transaction. By adding a deferred rollback, it will be executed or a no-op if a commit succeeded.
> database: Deferred Transaction Rollback

- redis/client.go
- utils/utils.go
A [generic max function](https://pkg.go.dev/builtin#max) was added to Go in version 1.21, making the `utils.MaxInt` obsolete. Outside, it was not used in neither icingadb, icinga-notifications nor icinga-kubernetes.
```
$ for project in icingadb icinga-notifications icinga-kubernetes; do pushd "$project"; git checkout main; git pull; grep -r "MaxInt"; popd; done
~/git/github.com/Icinga/icingadb ~/git/github.com/Icinga
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
cmd/icingadb-migrate/cache.go:                          checkpoint = math.MaxInt64 // start from the largest (possible) ID
cmd/icingadb-migrate/main.go:           ht.fromId = math.MaxInt64
grep: icingadb-migrate: binary file matches
grep: icingadb: binary file matches
~/git/github.com/Icinga …
```
> utils: Drop MaxInt

- objectpacker/objectpacker.go
> objectpacker/objectpacker.go:91:55: G115: integer overflow conversion int -> uint64 (gosec)
>                 if err := binary.Write(out, binary.BigEndian, uint64(l)); err != nil {
> objectpacker: Assure gosec that in.Len() to uint64 cannot overflow

- config/config_test.go
- config/tls_test.go
This PR introduces tests for the `ParseFlags()`, `FromYAMLFile()` and `TLS.MakeConfig()` functions:
* Verifies that command-line flags are correctly parsed into a struct.
* Error propagation from defaults.Set().
* **Nil pointer argument**: Tests calling FromYAMLFile with a nil pointer argument.
* **Nil argument**: Tests calling FromYAMLFile with a nil argument.
* **Simple YAML**: Tests parsing a simple YAML file.
* **Inlined YAML**: Tests parsing a YAML file with inlined fields.
* **Embedded YAML**: Tests parsing a YAML file with embedded fields.
* **Defaults**: Tests parsing a YAML file with default values.
* **Overriding defaults**: Tests parsing a YAML file overriding default values.
* **Empty YAML**: Tests parsing an empty YAML file.
* **Empty YAML with directive separator**: Tests …
> Test `config`

- retry/retry.go
They aren't of type *pq.Error, but they're clearly database errors.
closes Icinga/icingadb#620
("fixes" will be a dependency update.)
> Actually retry every database error, including "pq: ..."

- redis/client.go
We need to retry the XREAD commands in the following situations:
- If Go Redis returns redis.Nil, it means no data was read from Redis — e.g. when the keys don’t exist yet, and we will need to retry the operation again.
- To prevent surpassing Go Redis's internal maximum retries or any other I/O timeouts [^1], it's important to set a block timeout greater than zero for the XREAD commands, see the `a.Block` assignment. However, setting a block timeout means that Go Redis will not retry any errors internally and will instead return an I/O timeout error when exceeding the timeout. Thus, we need to handle this here and retry it again. On the other hand, an I/O timeout could also mean a `context.DeadlineExceeded` error, which is not retryable, so we have to check for context termination by …
> redis.Client#XReadUntilResult(): also re-try timeout errors

- database/db.go
A key finding of Icinga/icingadb#800 was that committing a transaction does not necessarily have to respect the context of the transaction, depending on the database driver. As @lippserd suggested there, I have added notes to the documentation of all relevant database functions.
> database: Document context limitations of Tx.Commit()

- config/config.go
- config/contracts.go
This reverts commit f25f8a03e301395f9bf3873783970f8e502479a7, reversing changes made to a2fd4d4fc03652d0871e4800eeb2f2b005d6f08b.
While the changes relax the necessary checks for passing a valid pointer, they complicate the tests and still allow non-construct pointer types that implement the validator interface to pass. This negates the benefits, making it simpler to validate the pointer argument in a function as previously done.
refs #72
> Revert "Merge pull request #72 from Icinga/reflectPtr"

- config/config.go
- config/contracts.go
- config/tls.go
This PR adds example usages for `config` package components and also adds package docs.
refs #62
> Document `config`

- config/config.go
- config/config_test.go
Previously, the libraries used, i.e. `jessevdk/go-flags` and `creasty/defaults`, returned an error if the specified argument was not a struct pointer. We now do this in our validation.
The PR also introduces some minor code quality changes.
> Also validate that arguments to `config` functions are struct pointers

- database/db.go
- database/db_test.go
- redis/client.go
- redis/client_test.go
The idea of a more informative connection information string was brought up in [#50](https://github.com/Icinga/icinga-go-library/pull/50#pullrequestreview-2213720430). Currently, at least Icinga DB and Icinga Notifications are logging their connection target after startup. This information, however, is quite vague and was now extended to contain, e.g., if TLS is used, the username, the 
```
INFO    icingadb        Connecting to database at 'mysql://icingadb@localhost:3306/icingadb'
INFO    icingadb        Connecting to Redis at 'redis://localhost:6380'
```
Furthermore, the zapcore.ObjectMarshaler interface was implemented, allowing both *db.DB and *redis.Client to be used as a zap logging field, showing the address.
> db.DB/redis.Client: Details in Address for GetAddr

- logging/config.go
- logging/config_test.go
- testutils/testutils.go
Previously, commit ccf002a introduced `UnmarshalText()` to allow `Options` to be parsed by the `env` package. With this change, the `go-yaml` package detects that `Options` should be decoded by that unmarshaller [^1] [^2]. However, since `Options` is not a text type, `go-yaml` does not use the unmarshaller [^3], resulting in unmarshalling failures [^4]. This change implements `UnmarshalYAML()` on `Options`, which is tried before `UnmarshalText()` [^5], restoring unmarshalling functionality.
Additionally, it's essential that `Options` is no longer inlined within `Config`, ensuring that `UnmarshalYAML()` receives only the relevant `options` section instead of the entire YAML. Interestingly, this used to work previously.
[^1]: https://github.com/goccy/go-yaml/blob/v1.12.0/decode.go#L703 …
> `logging#Config`: Fix `Options` can no longer be parsed by `go-yaml`

- config/config.go
- config/config_test.go
- config/contracts.go
This PR introduces `config.Load()` that supports configuration loading  in three scenarios:
1. Load configuration solely from YAML files when no relevant environment variables are set.
2. Combine YAML file and environment variable configurations, allowing environment variables to supplement or override possible incomplete YAML configurations.
3. Load entirely from environment variables if the default YAML config file is absent and no specific config path is provided by the user.
`config.FromYAMLFile()` is still called first but continuation with `config.FromEnv()` is allowed by handling:
* **ErrInvalidConfiguration**: The configuration may be incomplete and will be revalidated in `config.FromEnv()`.
* **Non-existent file errors**: If no explicit config path is set, fallback to environment …
> Support loading configuration from both YAML files and env vars

- database/db.go
Use provided methods to set query parameters instead of accessing directly to the map entries.
> Use methods to set query parameters

- logging/logging.go
Once a zap logger is created, its minimum log level is set in its core. It is possible to log at this level or at a higher level, for example, when setting info, one can log at info or error. However, it is not possible to decrease the level of the logger.
This can be useful when the user has configured a high default level, but some messages still need to be logged without giving them a ridiculously high level, e.g., a start log entry with a version string as an error log entry.
> logging: ForceLog option to log all messages

- config/tls.go
Unset the TLS private key environment variable after usage. Since this field can store both the path to a private key as well as a raw private key, it should be unset to not be available to child processes, e.g., an Icinga Notifications channel plugin.
> config: unset TLS Key environment variable

- database/utils.go
- types/int.go
- types/int_test.go
- types/string.go
- types/string_test.go
- utils/utils.go
- utils/utils_test.go
This PR imports the `internal/utils` package from Icinga Notifications into `utils` for general purpose functions and into `database` for database-related utility functions. The commit history was kept, but messages were slightly altered since the original messages often referred changes outside the `internal/utils` package.
My motivation for this merge was to use a utility function already implemented, but residing in the wrong project's utility package. Since the IGL is the place for common code, I would like to get rid of utility packages outside this repository.
<details><summary>Steps performed to create this PR</summary>
<p>
Within the `icinga-notifications` repository.
```sh
$ cd internal/utils
$ git format-patch --relative --root -- ./
0001-Introduce-utils-package.patch …
```
> Import Icinga Notifications `internal/utils`

- database/db.go
- database/driver.go
- redis/client.go
database,redis: More verbosity in OnRetryableError
The OnRetryableError functions came with conditions to only log the
error if it had changed since the last iteration. While this keeps the
log file clean, it hides reoccurring errors and makes it harder to
identify specific errors.
The changed version always logs the reoccurring error and also includes
the duration since the start and the current attempt.
> database,redis: More verbosity in OnRetryableError

- logging/error.go
- logging/journald_core.go
- logging/journald_core_test.go
Our journald zapcore.Core logs every zap field as a journald field. This has the disadvantage that these fields do not shown up in the default journalctl output, effectively hiding errors. While this is documented, it is not the expected behavior for most users, resulting in incomplete bug reports.
This change introduces a new set of zap fields to be also included in the journald message. Currently, only the "error" field gets this special treatment, allowing errors to be displayed.
An exemplary Icinga DB log message would change as follows while still containing the ICINGADB_ERROR field.
> database: Can't connect to database. Retrying
> database: Can't connect to database. Retrying	error="dial tcp [::1]:5432: connect: connection refused"
As a drive-by change, the package-global variable …
> logging: Include error field in journald message, Fix key encoding of all fields for journaldCore

- retry/retry.go
Drop the unused and potentially faulty retry.ResetTimeout function.
The retry.ResetTimeout function relied that the time.Timer's internal channel is asynchronous. This behavior changed with Go 1.23, resulting in a now blocking t.C call[^0].
Since there is no usage of this function anymore[^1][^2] and the current implementation is error prone, it was removed.
```
$ for i in icinga{db,-notifications,-kubernetes}; do pushd $i; git pull; git grep ResetTimeout | wc -l; popd; done
~/git/github.com/Icinga/icingadb ~/git/github.com/Icinga
Already up to date.
0
~/git/github.com/Icinga
~/git/github.com/Icinga/icinga-notifications ~/git/github.com/Icinga
Already up to date.
0
~/git/github.com/Icinga
~/git/github.com/Icinga/icinga-kubernetes ~/git/github.com/Icinga
Already up to date.
0 …
```
> retry: Remove ResetTimeout function

- logging/logging.go
It's kinda annoying that the tests spams the GHA logs with lots of log messages even though the tests aren't failing, see [^1] as an example. Since zap already provides a logger that logs to the testing.T instance, allow overriding the core factory to use that logger instead. This way, the logs are only visible when the test fails or when running the tests with the `-v` flag.
```bash
~/Workspace/go/icinga-go-library (logging-with-factory ✗) go test './logging/...'
ok  	github.com/icinga/icinga-go-library/logging	0.212s
~/Workspace/go/icinga-go-library (logging-with-factory ✗) go test -v './logging/...'
...
=== RUN   TestNewLoggingWithFactory
=== PAUSE TestNewLoggingWithFactory
=== CONT  TestNewLoggingWithFactory
logger.go:146: 2025-09-04T17:38:01.177+0200	DEBUG	my-component	This is a …
```
> logging: allow to provide custom core factory func
